apiVersion: v1
kind: Service
metadata:
    name: wizecontentodata-service
    namespace: development
    labels:
      app: wizecontentodata
spec:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort:  80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
    selector:
        app: wizecontentodata